default: &default
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  
development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: weather_app_test

production:
  <<: *default
  adapter: postgresql
  database: weather_app_production
  username: weather_app
  password: <%= ENV['WEATHER_APP_DATABASE_PASSWORD'] %>